# Generated by Django 5.2.15 on 2026-07-05 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Powder', 'Powder'), ('Gel', 'Gel'), ('Ointment', 'Ointment')], max_length=20)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('default_dose', models.CharField(blank=True, max_length=100)),
                ('default_frequency', models.CharField(blank=True, choices=[('Once daily', 'Once daily'), ('Twice daily', 'Twice daily'), ('Thrice daily', 'Thrice daily'), ('Four times daily', 'Four times daily'), ('Every 6 hours', 'Every 6 hours'), ('Every 8 hours', 'Every 8 hours'), ('Every 12 hours', 'Every 12 hours'), ('Weekly', 'Weekly'), ('As needed', 'As needed')], max_length=30)),
                ('default_duration', models.CharField(blank=True, max_length=50)),
                ('default_timing', models.CharField(blank=True, choices=[('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('With Meal', 'With Meal'), ('Empty Stomach', 'Empty Stomach'), ('At Bedtime', 'At Bedtime'), ('As Needed', 'As Needed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=300)),
                ('specialization', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.TextField()),
                ('clinic_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('age_unit', models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], default='Years', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('chief_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('pulse', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Final', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=50)),
                ('timing', models.CharField(default='After Meal', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.prescription')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('chief_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('follow_up_days', models.IntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prescriptiontemplate'),
        ),
        migrations.CreateModel(
            name='TemplateMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=50)),
                ('timing', models.CharField(default='After Meal', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicine')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.prescriptiontemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
