# Generated by Django 6.0.6 on 2026-07-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='investigation',
            field=models.TextField(blank=True),
        ),
    ]
